/**
 * 애플리케이션의 루트 레이아웃 컴포넌트
 * - 전체 애플리케이션의 기본 구조를 정의
 * - 폰트 설정 및 전역 스타일 적용
 * - LayoutWrapper를 통해 사이드바와 메인 콘텐츠 구조 제공
 */

// Geist 폰트 임포트
import localFont from "next/font/local";
// 전역 스타일시트 임포트
import "./globals.css";
import NavBar from "@/components/navBar";
import styles from './page.module.css';

/**
 * Geist Sans 폰트 설정
 * - 가변 폰트로 다양한 두께 지원
 * - CSS 변수로 폰트 패밀리 설정
 */
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

/**
 * Geist Mono 폰트 설정
 * - 모노스페이스 폰트로 코드 블록 등에 사용
 * - CSS 변수로 폰트 패밀리 설정
 */
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// 메타데이터 설정
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * 루트 레이아웃 컴포넌트
 * @param {Object} props - 컴포넌트 props
 * @param {React.ReactNode} props.children - 자식 컴포넌트들
 * @returns {JSX.Element} 애플리케이션의 기본 레이아웃
 */
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* 폰트 변수를 body에 적용 */}
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={styles['examples-upcoming-web']}>
        <NavBar />
        {children}
        </div>
      </body>
    </html>
  );
}
